version: '3.8'

# Development dependencies only - run the app locally
# Usage: docker-compose -f docker-compose-dev.yml up -d

services:
  redis:
    image: redis:7-alpine
    container_name: pr-agent-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - pr-agent-dev

  # Redis Commander - Web UI for Redis debugging
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: pr-agent-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - pr-agent-dev

  # Optional: Prometheus for metrics collection during development
  prometheus:
    image: prom/prometheus:latest
    container_name: pr-agent-prometheus-dev
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_dev_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - pr-agent-dev
    profiles:
      - metrics

  # Optional: Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: pr-agent-grafana-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_dev_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - pr-agent-dev
    profiles:
      - metrics

volumes:
  redis_dev_data:
    driver: local
  prometheus_dev_data:
    driver: local
  grafana_dev_data:
    driver: local

networks:
  pr-agent-dev:
    driver: bridge